; ESPHomeAPI example: Update (firmware)
;   pio run -e esp32dev -t upload && pio device monitor

[platformio]
default_envs = esp32dev

[env]
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../../lib
build_flags = -std=gnu++17
build_src_flags =
    -DESPHOME_API_SERIAL_BRIDGE
    -I../../lib/ESPHomeAPI/src
    -I../_common
    -include serial_log_bridge_install.h
build_unflags = -std=gnu++11

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
